#!/usr/bin/env python3
"""
Generate a BookSim2 text config for topology=chiplet_mesh from JSON.

Supports:
  - Legacy shape: root keys `chiplet` + `sim` (see chiplet_spec.sample.json).
  - v1 shape: `schema_version` + `mesh_chiplet` + `d2d_cdc` + `sim`
    (see mesh_chiplet_spec.sample.json, mesh_chiplet.schema.json).

Routing is always emitted as chiplet_mesh + dim_order_chiplet_mesh.

Usage:
  python3 tools/chiplet_spec_to_config.py path/to/spec.json -o out.cfg
"""
from __future__ import annotations

import argparse
import json
import sys
import warnings
from pathlib import Path


def die_k_list(spec: dict) -> list[int]:
    ch = spec.get("chiplet") or {}
    x = int(ch["x"])
    y = int(ch["y"])
    d = x * y
    if "die_k" in ch:
        dk = [int(v) for v in ch["die_k"]]
        if len(dk) == 1:
            return dk * d
        if len(dk) != d:
            raise ValueError(f"chiplet.die_k length must be 1 or {x*y} (row-major cy*cx+cx)")
        return dk
    k = int(ch.get("k", 2))
    return [k] * d


def die_intra_list(spec: dict, d: int) -> list[int] | None:
    ch = spec.get("chiplet") or {}
    if "die_intra_latency" not in ch:
        return None
    v = ch["die_intra_latency"]
    if isinstance(v, int):
        if v <= 0:
            return None
        lst = [v] * d
    else:
        lst = [int(x) for x in v]
        if len(lst) == 1:
            lst = lst * d
        elif len(lst) != d:
            raise ValueError(
                "chiplet.die_intra_latency length must be 1 or chiplet_x*chiplet_y"
            )
        if all(x <= 0 for x in lst):
            return None
    return lst


def cdc_lines(ch: dict, d: int) -> list[str]:
    if not ch.get("cdc_enable"):
        return []
    out = [
        "",
        "chiplet_cdc_enable = 1;",
        f"chiplet_cdc_fifo_depth = {int(ch.get('cdc_fifo_depth', 64))};",
        f"chiplet_cdc_sync_cycles = {int(ch.get('cdc_sync_cycles', 2))};",
        f"chiplet_cdc_credit_sync_cycles = {int(ch.get('cdc_credit_sync_cycles', 2))};",
        f"chiplet_cdc_gray_fifo = {int(ch.get('cdc_gray_fifo', 0))};",
        f"chiplet_cdc_gray_stages = {int(ch.get('cdc_gray_stages', 2))};",
    ]
    if "die_clock_period" in ch:
        dcp = ch["die_clock_period"]
        if isinstance(dcp, int):
            dcp = [dcp]
        lst = [int(v) for v in dcp]
        if len(lst) == 1:
            lst = lst * d
        elif len(lst) != d:
            raise ValueError(
                "chiplet.die_clock_period length must be 1 or chiplet_x*chiplet_y"
            )
        out.append(
            f"chiplet_die_clock_period = {{{','.join(str(v) for v in lst)}}};"
        )
    if "die_clock_phase" in ch:
        dph = ch["die_clock_phase"]
        if isinstance(dph, int):
            dph = [dph]
        lst = [int(v) for v in dph]
        if len(lst) == 1:
            lst = lst * d
        elif len(lst) != d:
            raise ValueError(
                "chiplet.die_clock_phase length must be 1 or chiplet_x*chiplet_y"
            )
        out.append(
            f"chiplet_die_clock_phase = {{{','.join(str(v) for v in lst)}}};"
        )
    return out


def sim_lines(sim: dict) -> list[str]:
    return [
        "",
        f"num_vcs     = {int(sim.get('num_vcs', 8))};",
        f"vc_buf_size = {int(sim.get('vc_buf_size', 8))};",
        f"wait_for_tail_credit = {int(sim.get('wait_for_tail_credit', 1))};",
        "",
        f"vc_allocator = {sim.get('vc_allocator', 'islip')};",
        f"sw_allocator = {sim.get('sw_allocator', 'islip')};",
        f"alloc_iters  = {int(sim.get('alloc_iters', 1))};",
        "",
        f"credit_delay   = {int(sim.get('credit_delay', 2))};",
        f"routing_delay  = {int(sim.get('routing_delay', 0))};",
        f"vc_alloc_delay = {int(sim.get('vc_alloc_delay', 1))};",
        f"sw_alloc_delay = {int(sim.get('sw_alloc_delay', 1))};",
        "",
        f"input_speedup     = {int(sim.get('input_speedup', 2))};",
        f"output_speedup    = {int(sim.get('output_speedup', 1))};",
        f"internal_speedup  = {float(sim.get('internal_speedup', 1.0))};",
        "",
        f"traffic = {sim.get('traffic', 'uniform')};",
        f"packet_size = {int(sim.get('packet_size', 4))};",
        "",
        f"sim_type = {sim.get('sim_type', 'latency')};",
        f"injection_rate = {float(sim.get('injection_rate', 0.002))};",
        f"latency_thres = {float(sim.get('latency_thres', 5000.0))};",
        "",
    ]


def emit_legacy_chiplet(spec: dict) -> str:
    ch = spec.get("chiplet") or {}
    sim = spec.get("sim") or {}
    x = int(ch["x"])
    y = int(ch["y"])
    connect = ch.get("connect", "x")
    dk = die_k_list(spec)
    d = x * y
    intra = die_intra_list(spec, d)

    lines = [
        "// Generated by chiplet_spec_to_config.py (legacy chiplet + sim)",
        "topology = chiplet_mesh;",
        "routing_function = dim_order_chiplet_mesh;",
        "",
        f"chiplet_x = {x};",
        f"chiplet_y = {y};",
        f"chiplet_k = {dk[0]};",
        f"chiplet_connect = {connect};",
        "",
        f"chiplet_die_k = {{{','.join(str(v) for v in dk)}}};",
    ]
    if intra is not None:
        lines.append(
            f"chiplet_die_intra_latency = {{{','.join(str(v) for v in intra)}}};"
        )
    lines += [
        "",
        f"chiplet_intra_latency = {int(ch.get('intra_latency', 1))};",
        f"chiplet_d2d_latency = {int(ch.get('d2d_latency', 2))};",
    ]
    lines += cdc_lines(ch, d)
    lines += sim_lines(sim)
    return "\n".join(lines)


def _validate_adjacent_k(dk: list[int], x: int, y: int, connect: str) -> None:
    if connect not in ("x", "xy"):
        raise ValueError("connect must be 'x' or 'xy'")
    for cy in range(y):
        for cx in range(x - 1):
            d0 = cy * x + cx
            d1 = cy * x + cx + 1
            if dk[d0] != dk[d1]:
                raise ValueError(
                    f"chiplet_connect=x: adjacent dies {d0} and {d1} must have same k "
                    f"(got {dk[d0]} vs {dk[d1]})"
                )
    if connect == "xy":
        for cy in range(y - 1):
            for cx in range(x):
                d0 = cy * x + cx
                d1 = (cy + 1) * x + cx
                if dk[d0] != dk[d1]:
                    raise ValueError(
                        f"chiplet_connect=xy: adjacent dies {d0} and {d1} must have same k "
                        f"(got {dk[d0]} vs {dk[d1]})"
                    )


def _heterogeneous_clocks(periods: list[int], phases: list[int]) -> bool:
    return any(p != 1 for p in periods) or any(ph != 0 for ph in phases)


def _cdc_lines_v1(
    d2d: dict,
    d: int,
    periods: list[int],
    phases: list[int],
) -> list[str]:
    gray = d2d.get("gray") or {}
    gray_on = 1 if gray.get("enabled") else 0
    gray_stages = int(gray.get("stages", 2))
    out = [
        "",
        "chiplet_cdc_enable = 1;",
        f"chiplet_cdc_fifo_depth = {int(d2d.get('fifo_depth', 64))};",
        f"chiplet_cdc_sync_cycles = {int(d2d.get('flit_sync_cycles', 2))};",
        f"chiplet_cdc_credit_sync_cycles = {int(d2d.get('credit_sync_cycles', 2))};",
        f"chiplet_cdc_gray_fifo = {gray_on};",
        f"chiplet_cdc_gray_stages = {gray_stages};",
        f"chiplet_die_clock_period = {{{','.join(str(v) for v in periods)}}};",
        f"chiplet_die_clock_phase = {{{','.join(str(v) for v in phases)}}};",
    ]
    return out


def emit_mesh_chiplet_v1(spec: dict) -> str:
    ver = spec.get("schema_version")
    if ver != "1.0":
        raise ValueError(f"Unsupported schema_version: {ver!r} (expected '1.0')")

    routing = spec.get("routing") or {}
    if routing.get("topology") != "chiplet_mesh" or routing.get("function") != "dim_order_chiplet_mesh":
        warnings.warn(
            "routing.topology/function differ from chiplet_mesh + "
            "dim_order_chiplet_mesh; generator overwrites with fixed values.",
            stacklevel=2,
        )

    mc = spec["mesh_chiplet"]
    grid = mc["grid"]
    x, y = int(grid["x"]), int(grid["y"])
    d = x * y
    connect = mc.get("connect", "x")
    dies = mc["dies"]
    if len(dies) != d:
        raise ValueError(f"mesh_chiplet.dies length must be grid.x*grid.y = {d}")

    dk: list[int] = []
    periods: list[int] = []
    phases: list[int] = []
    intra_per_die: list[int] = []
    default_intra = int(mc.get("intra_latency", 1))

    for i, die in enumerate(dies):
        if "id" in die and int(die["id"]) != i:
            raise ValueError(f"dies[{i}].id must be {i} when present (row-major order)")
        dk.append(int(die["k"]))
        clk = die["clock"]
        periods.append(int(clk["period"]))
        phases.append(int(clk["phase"]))
        intra_per_die.append(int(die.get("intra_latency", default_intra)))

    _validate_adjacent_k(dk, x, y, connect)

    hetero = _heterogeneous_clocks(periods, phases)
    d2d = spec.get("d2d_cdc") or {}
    cdc_on = bool(d2d.get("enabled"))
    if hetero and not cdc_on:
        raise ValueError(
            "Non-default die clocks (period!=1 or phase!=0) require d2d_cdc.enabled = true "
            "(BookSim rejects chiplet_cdc_enable = 0 with heterogeneous clocks)."
        )
    if cdc_on and not hetero:
        # Allowed: CDC on with all 1,0 (extra D2D latency model only).
        pass

    d2d_lat = int(mc.get("d2d_wire_latency", 2))

    lines = [
        "// Generated by chiplet_spec_to_config.py (mesh_chiplet v1)",
        "topology = chiplet_mesh;",
        "routing_function = dim_order_chiplet_mesh;",
        "",
        f"chiplet_x = {x};",
        f"chiplet_y = {y};",
        f"chiplet_k = {dk[0]};",
        f"chiplet_connect = {connect};",
        "",
        f"chiplet_die_k = {{{','.join(str(v) for v in dk)}}};",
    ]

    if any(v != default_intra for v in intra_per_die):
        lines.append(
            f"chiplet_die_intra_latency = {{{','.join(str(v) for v in intra_per_die)}}};"
        )

    lines += [
        "",
        f"chiplet_intra_latency = {default_intra};",
        f"chiplet_d2d_latency = {d2d_lat};",
    ]

    if cdc_on:
        lines += _cdc_lines_v1(d2d, d, periods, phases)

    sim = spec.get("sim") or {}
    lines += sim_lines(sim)
    return "\n".join(lines)


def emit(spec: dict) -> str:
    if "mesh_chiplet" in spec:
        return emit_mesh_chiplet_v1(spec)
    if "chiplet" in spec:
        return emit_legacy_chiplet(spec)
    raise ValueError("JSON must contain 'mesh_chiplet' (v1) or 'chiplet' (legacy) root object")


def main() -> None:
    ap = argparse.ArgumentParser(description="JSON chiplet spec -> BookSim config")
    ap.add_argument("spec_json", type=Path)
    ap.add_argument("-o", "--output", type=Path, required=True)
    args = ap.parse_args()
    spec = json.loads(args.spec_json.read_text(encoding="utf-8"))
    args.output.write_text(emit(spec), encoding="utf-8")
    print(f"Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
