#!/usr/bin/env python3
"""
Generate a BookSim2 text config for topology=chiplet_mesh from JSON.
Intended for GUIs / automation; schema is documented in chiplet_spec.sample.json.

Usage:
  python3 tools/chiplet_spec_to_config.py path/to/spec.json -o out.cfg ./booksim out.cfg
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


def die_k_list(spec: dict) -> list[int]:
    ch = spec.get("chiplet") or {}
    x = int(ch["x"])
    y = int(ch["y"])
    d = x * y
    if "die_k" in ch:
        dk = [int(v) for v in ch["die_k"]]
        if len(dk) == 1:
            return dk * d
        if len(dk) != d:
            raise ValueError(f"chiplet.die_k length must be 1 or {x*y} (row-major cy*cx+cx)")
        return dk
    k = int(ch.get("k", 2))
    return [k] * d


def die_intra_list(spec: dict, d: int) -> list[int] | None:
    ch = spec.get("chiplet") or {}
    if "die_intra_latency" not in ch:
        return None
    v = ch["die_intra_latency"]
    if isinstance(v, int):
        if v <= 0:
            return None
        lst = [v] * d
    else:
        lst = [int(x) for x in v]
        if len(lst) == 1:
            lst = lst * d
        elif len(lst) != d:
            raise ValueError(
                "chiplet.die_intra_latency length must be 1 or chiplet_x*chiplet_y"
            )
        if all(x <= 0 for x in lst):
            return None
    return lst


def emit(spec: dict) -> str:
    ch = spec.get("chiplet") or {}
    sim = spec.get("sim") or {}
    x = int(ch["x"])
    y = int(ch["y"])
    connect = ch.get("connect", "x")
    dk = die_k_list(spec)
    d = x * y
    intra = die_intra_list(spec, d)

    lines = [
        "// Generated by chiplet_spec_to_config.py",
        "topology = chiplet_mesh;",
        'routing_function = dim_order_chiplet_mesh;',
        "",
        f"chiplet_x = {x};",
        f"chiplet_y = {y};",
        f"chiplet_k = {dk[0]};",
        f"chiplet_connect = {connect};",
        "",
        # BookSim lexer: no spaces after commas inside { ... }
        f"chiplet_die_k = {{{','.join(str(v) for v in dk)}}};",
    ]
    if intra is not None:
        lines.append(
            f"chiplet_die_intra_latency = {{{','.join(str(v) for v in intra)}}};"
        )
    lines += [
        "",
        f"chiplet_intra_latency = {int(ch.get('intra_latency', 1))};",
        f"chiplet_d2d_latency = {int(ch.get('d2d_latency', 2))};",
        "",
        f"num_vcs     = {int(sim.get('num_vcs', 8))};",
        f"vc_buf_size = {int(sim.get('vc_buf_size', 8))};",
        f"wait_for_tail_credit = {int(sim.get('wait_for_tail_credit', 1))};",
        "",
        f"vc_allocator = {sim.get('vc_allocator', 'islip')};",
        f"sw_allocator = {sim.get('sw_allocator', 'islip')};",
        f"alloc_iters  = {int(sim.get('alloc_iters', 1))};",
        "",
        f"credit_delay   = {int(sim.get('credit_delay', 2))};",
        f"routing_delay  = {int(sim.get('routing_delay', 0))};",
        f"vc_alloc_delay = {int(sim.get('vc_alloc_delay', 1))};",
        f"sw_alloc_delay = {int(sim.get('sw_alloc_delay', 1))};",
        "",
        f"input_speedup     = {int(sim.get('input_speedup', 2))};",
        f"output_speedup    = {int(sim.get('output_speedup', 1))};",
        f"internal_speedup  = {float(sim.get('internal_speedup', 1.0))};",
        "",
        f"traffic = {sim.get('traffic', 'uniform')};",
        f"packet_size = {int(sim.get('packet_size', 4))};",
        "",
        f"sim_type = {sim.get('sim_type', 'latency')};",
        f"injection_rate = {float(sim.get('injection_rate', 0.002))};",
        f"latency_thres = {float(sim.get('latency_thres', 5000.0))};",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="JSON chiplet spec -> BookSim config")
    ap.add_argument("spec_json", type=Path)
    ap.add_argument("-o", "--output", type=Path, required=True)
    args = ap.parse_args()
    spec = json.loads(args.spec_json.read_text(encoding="utf-8"))
    args.output.write_text(emit(spec), encoding="utf-8")
    print(f"Wrote {args.output}", file=sys.stderr)


if __name__ == "__main__":
    main()
